import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' }
];

const translations = {
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.acupressure': 'Acupressão',
    'nav.breathing': 'Respiração',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporativo',
    'nav.blog': 'Blog',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Sons',
    'nav.progress': 'Progresso',
    'nav.personalization': 'Personalização',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',

    // Home Page
    'home.hero.title': 'XZenPress Wellness',
    'home.hero.subtitle': 'Plataforma completa de bem-estar integrativa com acupressão MTC, Craniopuntura, respiração 4-7-8 e cromoterapia avançada',
    'home.hero.startNow': 'Começar Agora',
    'home.hero.createAccount': 'Criar Conta',

    // Home Features
    'home.feature.acupressure.title': 'Acupressão MTC',
    'home.feature.acupressure.desc': '20 pontos terapêuticos da Medicina Tradicional Chinesa para alívio natural',
    'home.feature.breathing.title': 'Respiração 4-7-8',
    'home.feature.breathing.desc': 'Técnica científica de respiração com cromoterapia sincronizada',
    'home.feature.cranio.title': 'Craniopuntura',
    'home.feature.cranio.desc': 'Pontos especializados para sistema nervoso e função cerebral',
    'home.feature.chromotherapy.title': 'Cromoterapia Avançada',
    'home.feature.chromotherapy.desc': 'Cores terapêuticas sincronizadas com respiração para potencializar efeitos',
    'home.feature.sounds.title': 'Sons Harmonizantes',
    'home.feature.sounds.desc': 'Biblioteca de sons relaxantes com integração Spotify Premium',
    'home.feature.consultation.title': 'Consulta Especializada',
    'home.feature.consultation.desc': 'Atendimento personalizado via WhatsApp com profissional qualificado',

    'home.features.title': 'Recursos Terapêuticos',
    'home.features.subtitle': 'Combine técnicas milenares com tecnologia moderna para máximo bem-estar integrativo',

    'home.cta.title': 'Transforme sua Qualidade de Vida',
    'home.cta.subtitle': 'Junte-se a milhares de pessoas que já descobriram o poder das terapias integrativas',
    'home.cta.demo': 'Experimentar Grátis',
    'home.cta.corporate': 'Soluções Corporativas',

    'home.compliance.title': 'Compliance Legal Completo',
    'home.compliance.subtitle': 'Atendimento integral à legislação brasileira de saúde mental corporativa com abordagem integrativa',

    // Acupressure Page
    'acupressure.title': 'Pontos de Acupressão',
    'acupressure.subtitle': 'Medicina Tradicional Chinesa e Craniopuntura com terapia integrativa: acupressão + respiração + cromoterapia',
    'acupressure.categories.all': 'Todos os Pontos',
    'acupressure.categories.general': 'MTC Geral',
    'acupressure.categories.cranio': 'Craniopuntura',
    'acupressure.categories.septicemia': 'Septicemia',
    'acupressure.categories.atm': 'ATM',
    'acupressure.select.title': 'Selecione um Ponto',
    'acupressure.select.subtitle': 'Clique em um ponto para ver detalhes e iniciar a terapia integrada',
    'acupressure.timer.start': 'Iniciar Terapia Integrada',
    'acupressure.timer.active': 'Terapia em Andamento',
    'acupressure.timer.switch': 'Trocar para Este Ponto',

    // Breathing Exercise
    'breathing.title': 'Respiração 4-7-8 com Cromoterapia',
    'breathing.inhale': 'Inspire',
    'breathing.hold': 'Segure',
    'breathing.exhale': 'Expire',
    'breathing.start': 'Iniciar Respiração',
    'breathing.stop': 'Parar',
    'breathing.reset': 'Reiniciar',
    'breathing.totalTime': 'Tempo Total',
    'breathing.phase': 'Fase',
    'breathing.phase.inhale.detail': 'Inspiração com azul calmante',
    'breathing.phase.hold.detail': 'Retenção com verde equilibrante',
    'breathing.phase.exhale.detail': 'Expiração com roxo energizante',

    'breathing.chromotherapy.title': 'Cromoterapia Científica',
    'breathing.chromotherapy.description': 'Cores terapêuticas sincronizadas com cada fase da respiração para potencializar os efeitos',
    'breathing.chromotherapy.blue': 'Azul Calmante',
    'breathing.chromotherapy.blue.desc': 'Ativa o sistema parassimpático, reduz pressão arterial e promove relaxamento profundo',
    'breathing.chromotherapy.green': 'Verde Equilibrante',
    'breathing.chromotherapy.green.desc': 'Equilibra o sistema nervoso, harmoniza emoções e promove estabilidade',
    'breathing.chromotherapy.magenta': 'Roxo Energizante',
    'breathing.chromotherapy.magenta.desc': 'Estimula liberação de endorfinas e promove transformação energética',

    'breathing.benefits.title': 'Benefícios Comprovados',
    'breathing.benefits.stress': 'Reduz estresse e ansiedade',
    'breathing.benefits.sleep': 'Melhora qualidade do sono',
    'breathing.benefits.focus': 'Aumenta foco e concentração',
    'breathing.benefits.pressure': 'Reduz pressão arterial',

    'breathing.science.title': 'Base Científica',
    'breathing.science.evidence': 'Evidências Científicas',
    'breathing.science.parasympathetic': 'Ativa sistema parassimpático',
    'breathing.science.cortisol': 'Reduz níveis de cortisol',
    'breathing.science.heartRate': 'Melhora variabilidade cardíaca',
    'breathing.science.gaba': 'Aumenta produção de GABA',
    'breathing.science.chromotherapy': 'Cromoterapia Integrada',
    'breathing.science.blue.effect': 'Azul reduz pressão arterial',
    'breathing.science.green.effect': 'Verde equilibra sistema nervoso',
    'breathing.science.magenta.effect': 'Roxo estimula endorfinas',
    'breathing.science.melatonin': 'Melhora produção de melatonina',

    // Premium Page
    'premium.hero.title': 'Desbloqueie Todo o Potencial',
    'premium.hero.subtitle': 'Acesso completo a consultas especializadas e recursos exclusivos de medicina integrativa',
    'premium.hero.upgrade': 'Fazer Upgrade',
    'premium.hero.active': 'Premium Ativo',

    'premium.features.title': 'Recursos Premium',
    'premium.features.available': 'Disponível',
    'premium.features.coming': 'Em Breve',

    'premium.features.whatsapp.title': 'Consulta WhatsApp',
    'premium.features.whatsapp.description': 'Atendimento personalizado com profissional qualificado',
    'premium.features.whatsapp.benefit1': 'Profissional com 15+ anos de experiência',
    'premium.features.whatsapp.benefit2': 'Resposta prioritária em até 24h',
    'premium.features.whatsapp.benefit3': 'Formulário detalhado para casos complexos',
    'premium.features.whatsapp.benefit4': 'Acompanhamento contínuo do caso',

    'premium.features.points.title': 'Pontos Exclusivos',
    'premium.features.points.description': '11 pontos especializados para casos específicos',
    'premium.features.points.benefit1': 'Septicemia: 3 pontos para purificação',
    'premium.features.points.benefit2': 'ATM: 3 pontos para articulação',
    'premium.features.points.benefit3': 'Cranio: 3 pontos para sistema nervoso',
    'premium.features.points.benefit4': 'Neurologia: 2 pontos avançados',

    'premium.features.chromotherapy.title': 'Cromoterapia Avançada',
    'premium.features.chromotherapy.description': 'Sequências personalizadas de cores terapêuticas',
    'premium.features.chromotherapy.benefit1': 'Perfis adaptativos de cores',
    'premium.features.chromotherapy.benefit2': 'Sincronização com biofeedback',
    'premium.features.chromotherapy.benefit3': 'Sequências personalizadas',
    'premium.features.chromotherapy.benefit4': 'Cores baseadas no estado emocional',

    'premium.features.sounds.title': 'Biblioteca Completa',
    'premium.features.sounds.description': 'Mais de 50 sons + integração Spotify',
    'premium.features.sounds.benefit1': 'Frequências binaurais terapêuticas',
    'premium.features.sounds.benefit2': 'Integração completa com Spotify',
    'premium.features.sounds.benefit3': 'Sons de alta qualidade',
    'premium.features.sounds.benefit4': 'Playlists curadas por especialistas',

    'premium.features.ai.title': 'Recomendações IA',
    'premium.features.ai.description': 'Inteligência artificial personalizada',
    'premium.features.ai.benefit1': 'Análise de padrões comportamentais',
    'premium.features.ai.benefit2': 'Recomendações personalizadas',
    'premium.features.ai.benefit3': 'Otimização automática de sessões',
    'premium.features.ai.benefit4': 'Insights preditivos de bem-estar',

    'premium.features.offline.title': 'Modo Offline',
    'premium.features.offline.description': 'Funcionalidades completas sem internet',
    'premium.features.offline.benefit1': 'Sincronização automática',
    'premium.features.offline.benefit2': 'Cache inteligente de conteúdo',
    'premium.features.offline.benefit3': 'Sessões offline completas',
    'premium.features.offline.benefit4': 'Backup automático de dados',

    'premium.plans.title': 'Planos Premium',
    'premium.plans.subtitle': 'Escolha o plano ideal para suas necessidades',
    'premium.plans.popular': 'Mais Popular',
    'premium.plans.save': 'Economize',
    'premium.plans.choose': 'Escolher Plano',

    'premium.plans.monthly.name': 'Premium Mensal',
    'premium.plans.monthly.period': '/mês',
    'premium.plans.monthly.feature1': 'Todos os pontos premium',
    'premium.plans.monthly.feature2': 'Consulta WhatsApp',
    'premium.plans.monthly.feature3': 'Sons exclusivos',
    'premium.plans.monthly.feature4': 'Cromoterapia avançada',
    'premium.plans.monthly.feature5': 'Suporte prioritário',

    'premium.plans.annual.name': 'Premium Anual',
    'premium.plans.annual.period': '/ano',
    'premium.plans.annual.feature1': 'Tudo do plano mensal',
    'premium.plans.annual.feature2': '2 meses grátis',
    'premium.plans.annual.feature3': 'Recomendações IA',
    'premium.plans.annual.feature4': 'Analytics avançados',
    'premium.plans.annual.feature5': 'Consultoria trimestral',

    'premium.plans.lifetime.name': 'Premium Vitalício',
    'premium.plans.lifetime.period': 'pagamento único',
    'premium.plans.lifetime.feature1': 'Acesso vitalício',
    'premium.plans.lifetime.feature2': 'Todas as futuras atualizações',
    'premium.plans.lifetime.feature3': 'Suporte VIP',
    'premium.plans.lifetime.feature4': 'Consultoria ilimitada',
    'premium.plans.lifetime.feature5': 'Acesso beta a novos recursos',

    'premium.payment.title': 'Finalizar Pagamento',
    'premium.payment.methods': 'Métodos de Pagamento',
    'premium.payment.back': 'Voltar aos Planos',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Instantâneo e seguro',
    'premium.payment.pix.title': 'Pagamento via PIX',
    'premium.payment.credit': 'Cartão',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Pagamento com Criptomoedas',

    'premium.testimonials.title': 'O que nossos usuários dizem',
    'premium.testimonials.maria': 'Transformou minha vida! A acupressão aliviou minhas dores crônicas em poucas semanas.',
    'premium.testimonials.joao': 'A respiração 4-7-8 me ajudou a controlar a ansiedade. Recomendo para todos!',
    'premium.testimonials.ana': 'Excelente para uso corporativo. Nossa equipe está muito mais relaxada e produtiva.',

    'premium.faq.title': 'Perguntas Frequentes',
    'premium.faq.q1': 'Posso cancelar a qualquer momento?',
    'premium.faq.a1': 'Sim, você pode cancelar sua assinatura a qualquer momento sem taxas adicionais.',
    'premium.faq.q2': 'Os pontos premium são seguros?',
    'premium.faq.a2': 'Todos os pontos são baseados na Medicina Tradicional Chinesa com 15+ anos de experiência clínica.',
    'premium.faq.q3': 'Funciona offline?',
    'premium.faq.a3': 'Sim, a versão premium inclui modo offline completo com sincronização automática.',
    'premium.faq.q4': 'Há garantia de resultados?',
    'premium.faq.a4': 'Oferecemos garantia de 30 dias. Se não ficar satisfeito, devolvemos seu dinheiro.',

    // Corporate Page
    'corporate.hero.title': 'Soluções Corporativas',
    'corporate.hero.subtitle': 'Bem-estar integrativo para empresas com compliance legal completo',
    'corporate.plans.title': 'Planos Corporativos',
    'corporate.analytics.title': 'Analytics Empresariais',
    'corporate.roi.title': 'ROI Comprovado',
    'corporate.roi.subtitle': 'Resultados mensuráveis em bem-estar corporativo',
    'corporate.roi.stress': 'Redução no estresse',
    'corporate.roi.absences': 'Menos faltas',
    'corporate.roi.engagement': 'Maior engajamento',
    'corporate.roi.return': 'Retorno do investimento',

    // Login Page
    'login.welcome': 'Bem-vindo de volta',
    'login.createAccount': 'Criar Conta',
    'login.subtitle.login': 'Entre na sua conta para acessar todos os recursos',
    'login.subtitle.register': 'Crie sua conta e comece sua jornada de bem-estar',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.confirmPassword': 'Confirmar Senha',
    'login.name': 'Nome',
    'login.forgotPassword': 'Esqueci minha senha',
    'login.noAccount': 'Não tem conta? Cadastre-se',
    'login.hasAccount': 'Já tem conta? Entre',
    'login.demo.title': 'Modo Demonstração',
    'login.demo.desc': 'Use qualquer email válido + senha com 6+ caracteres',
    'login.reset.title': 'Recuperar Senha',
    'login.reset.subtitle': 'Digite seu email para receber instruções',
    'login.reset.send': 'Enviar Email',
    'login.reset.back': 'Voltar ao Login',

    // WhatsApp Consultation
    'whatsapp.back': 'Voltar',
    'whatsapp.consultation.title': 'Consulta Especializada',
    'whatsapp.consultation.description': 'Formulário detalhado para atendimento personalizado via WhatsApp',
    'whatsapp.features.specialized.title': 'Atendimento Especializado',
    'whatsapp.features.specialized.subtitle': 'Casos complexos que precisam de atenção individual',
    'whatsapp.features.specialized.professional': 'Profissional com 15+ anos de experiência',
    'whatsapp.features.fast.title': 'Resposta Rápida',
    'whatsapp.features.fast.subtitle': 'Prioridade máxima de resposta',
    'whatsapp.features.direct.title': 'WhatsApp Direto',
    'whatsapp.features.direct.subtitle': 'Comunicação direta e personalizada',
    'whatsapp.when.title': 'Quando Buscar Ajuda',
    'whatsapp.when.chronic': 'Dores crônicas que não melhoram',
    'whatsapp.when.neurological': 'Problemas neurológicos complexos',
    'whatsapp.when.nonresponsive': 'Casos que não respondem aos pontos básicos',
    'whatsapp.when.personalized': 'Necessidade de protocolo personalizado',
    'whatsapp.testimonial.text': 'Atendimento excepcional! Resolveu minha dor crônica em poucas sessões.',
    'whatsapp.testimonial.author': 'Maria S., São Paulo',
    'whatsapp.form.title': 'Formulário de Consulta',
    'whatsapp.form.subtitle': 'Preencha os dados abaixo para receber atendimento especializado',
    'whatsapp.form.name': 'Nome Completo',
    'whatsapp.form.name.placeholder': 'Seu nome completo',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'seu@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '(11) 99999-9999',
    'whatsapp.form.urgency': 'Nível de Urgência',
    'whatsapp.form.urgency.select': 'Selecione a urgência',
    'whatsapp.form.urgency.low': 'Baixa - Consulta preventiva',
    'whatsapp.form.urgency.medium': 'Média - Desconforto moderado',
    'whatsapp.form.urgency.high': 'Alta - Dor significativa',
    'whatsapp.form.urgency.urgent': 'Urgente - Dor intensa',
    'whatsapp.form.medical.title': 'Informações Médicas',
    'whatsapp.form.medical.condition': 'Condição Principal',
    'whatsapp.form.medical.condition.placeholder': 'Ex: Enxaqueca crônica, ansiedade, dor nas costas',
    'whatsapp.form.medical.duration': 'Há quanto tempo tem os sintomas?',
    'whatsapp.form.medical.duration.placeholder': 'Ex: 2 anos, 6 meses, desde criança',
    'whatsapp.form.medical.symptoms': 'Descrição Detalhada dos Sintomas',
    'whatsapp.form.medical.symptoms.placeholder': 'Descreva em detalhes seus sintomas, quando aparecem, intensidade, etc.',
    'whatsapp.form.medical.treatments': 'Tratamentos Já Realizados',
    'whatsapp.form.medical.treatments.placeholder': 'Medicamentos, terapias, cirurgias, etc.',
    'whatsapp.form.medical.medications': 'Medicamentos Atuais',
    'whatsapp.form.medical.medications.placeholder': 'Liste todos os medicamentos que usa atualmente',
    'whatsapp.form.medical.schedule': 'Horário de Preferência',
    'whatsapp.form.medical.schedule.select': 'Selecione o melhor horário',
    'whatsapp.form.medical.schedule.morning': 'Manhã (8h-12h)',
    'whatsapp.form.medical.schedule.afternoon': 'Tarde (12h-18h)',
    'whatsapp.form.medical.schedule.evening': 'Noite (18h-22h)',
    'whatsapp.form.medical.schedule.anytime': 'Qualquer horário',
    'whatsapp.form.notice.title': 'Importante',
    'whatsapp.form.notice.text': 'Este formulário será enviado diretamente para nosso especialista via WhatsApp',
    'whatsapp.form.submit': 'Enviar para WhatsApp',
    'whatsapp.form.redirect': 'Você será redirecionado para o WhatsApp com sua mensagem pronta'
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.acupressure': 'Acupressure',
    'nav.breathing': 'Breathing',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporate',
    'nav.blog': 'Blog',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Sounds',
    'nav.progress': 'Progress',
    'nav.personalization': 'Personalization',
    'nav.login': 'Login',
    'nav.logout': 'Logout',

    // Home Page
    'home.hero.title': 'XZenPress Wellness',
    'home.hero.subtitle': 'Complete integrative wellness platform with TCM acupressure, Craniopuncture, 4-7-8 breathing and advanced chromotherapy',
    'home.hero.startNow': 'Start Now',
    'home.hero.createAccount': 'Create Account',

    // Home Features
    'home.feature.acupressure.title': 'TCM Acupressure',
    'home.feature.acupressure.desc': '20 therapeutic points from Traditional Chinese Medicine for natural relief',
    'home.feature.breathing.title': '4-7-8 Breathing',
    'home.feature.breathing.desc': 'Scientific breathing technique with synchronized chromotherapy',
    'home.feature.cranio.title': 'Craniopuncture',
    'home.feature.cranio.desc': 'Specialized points for nervous system and brain function',
    'home.feature.chromotherapy.title': 'Advanced Chromotherapy',
    'home.feature.chromotherapy.desc': 'Therapeutic colors synchronized with breathing to enhance effects',
    'home.feature.sounds.title': 'Harmonizing Sounds',
    'home.feature.sounds.desc': 'Relaxing sound library with Spotify Premium integration',
    'home.feature.consultation.title': 'Specialized Consultation',
    'home.feature.consultation.desc': 'Personalized care via WhatsApp with qualified professional',

    'home.features.title': 'Therapeutic Resources',
    'home.features.subtitle': 'Combine ancient techniques with modern technology for maximum integrative wellness',

    'home.cta.title': 'Transform Your Quality of Life',
    'home.cta.subtitle': 'Join thousands who have discovered the power of integrative therapies',
    'home.cta.demo': 'Try Free',
    'home.cta.corporate': 'Corporate Solutions',

    'home.compliance.title': 'Complete Legal Compliance',
    'home.compliance.subtitle': 'Full compliance with Brazilian corporate mental health legislation with integrative approach',

    // Acupressure Page
    'acupressure.title': 'Acupressure Points',
    'acupressure.subtitle': 'Traditional Chinese Medicine and Craniopuncture with integrative therapy: acupressure + breathing + chromotherapy',
    'acupressure.categories.all': 'All Points',
    'acupressure.categories.general': 'General TCM',
    'acupressure.categories.cranio': 'Craniopuncture',
    'acupressure.categories.septicemia': 'Septicemia',
    'acupressure.categories.atm': 'TMJ',
    'acupressure.select.title': 'Select a Point',
    'acupressure.select.subtitle': 'Click on a point to see details and start integrated therapy',
    'acupressure.timer.start': 'Start Integrated Therapy',
    'acupressure.timer.active': 'Therapy in Progress',
    'acupressure.timer.switch': 'Switch to This Point',

    // Breathing Exercise
    'breathing.title': '4-7-8 Breathing with Chromotherapy',
    'breathing.inhale': 'Inhale',
    'breathing.hold': 'Hold',
    'breathing.exhale': 'Exhale',
    'breathing.start': 'Start Breathing',
    'breathing.stop': 'Stop',
    'breathing.reset': 'Reset',
    'breathing.totalTime': 'Total Time',
    'breathing.phase': 'Phase',
    'breathing.phase.inhale.detail': 'Inhalation with calming blue',
    'breathing.phase.hold.detail': 'Retention with balancing green',
    'breathing.phase.exhale.detail': 'Exhalation with energizing purple',

    'breathing.chromotherapy.title': 'Scientific Chromotherapy',
    'breathing.chromotherapy.description': 'Therapeutic colors synchronized with each breathing phase to enhance effects',
    'breathing.chromotherapy.blue': 'Calming Blue',
    'breathing.chromotherapy.blue.desc': 'Activates parasympathetic system, reduces blood pressure and promotes deep relaxation',
    'breathing.chromotherapy.green': 'Balancing Green',
    'breathing.chromotherapy.green.desc': 'Balances nervous system, harmonizes emotions and promotes stability',
    'breathing.chromotherapy.magenta': 'Energizing Purple',
    'breathing.chromotherapy.magenta.desc': 'Stimulates endorphin release and promotes energy transformation',

    'breathing.benefits.title': 'Proven Benefits',
    'breathing.benefits.stress': 'Reduces stress and anxiety',
    'breathing.benefits.sleep': 'Improves sleep quality',
    'breathing.benefits.focus': 'Increases focus and concentration',
    'breathing.benefits.pressure': 'Lowers blood pressure',

    'breathing.science.title': 'Scientific Basis',
    'breathing.science.evidence': 'Scientific Evidence',
    'breathing.science.parasympathetic': 'Activates parasympathetic system',
    'breathing.science.cortisol': 'Reduces cortisol levels',
    'breathing.science.heartRate': 'Improves heart rate variability',
    'breathing.science.gaba': 'Increases GABA production',
    'breathing.science.chromotherapy': 'Integrated Chromotherapy',
    'breathing.science.blue.effect': 'Blue reduces blood pressure',
    'breathing.science.green.effect': 'Green balances nervous system',
    'breathing.science.magenta.effect': 'Purple stimulates endorphins',
    'breathing.science.melatonin': 'Improves melatonin production',

    // Premium Page
    'premium.hero.title': 'Unlock Full Potential',
    'premium.hero.subtitle': 'Complete access to specialized consultations and exclusive integrative medicine resources',
    'premium.hero.upgrade': 'Upgrade Now',
    'premium.hero.active': 'Premium Active',

    'premium.features.title': 'Premium Features',
    'premium.features.available': 'Available',
    'premium.features.coming': 'Coming Soon',

    'premium.features.whatsapp.title': 'WhatsApp Consultation',
    'premium.features.whatsapp.description': 'Personalized care with qualified professional',
    'premium.features.whatsapp.benefit1': 'Professional with 15+ years experience',
    'premium.features.whatsapp.benefit2': 'Priority response within 24h',
    'premium.features.whatsapp.benefit3': 'Detailed form for complex cases',
    'premium.features.whatsapp.benefit4': 'Continuous case monitoring',

    'premium.features.points.title': 'Exclusive Points',
    'premium.features.points.description': '11 specialized points for specific cases',
    'premium.features.points.benefit1': 'Septicemia: 3 purification points',
    'premium.features.points.benefit2': 'TMJ: 3 articulation points',
    'premium.features.points.benefit3': 'Cranio: 3 nervous system points',
    'premium.features.points.benefit4': 'Neurology: 2 advanced points',

    'premium.features.chromotherapy.title': 'Advanced Chromotherapy',
    'premium.features.chromotherapy.description': 'Personalized therapeutic color sequences',
    'premium.features.chromotherapy.benefit1': 'Adaptive color profiles',
    'premium.features.chromotherapy.benefit2': 'Biofeedback synchronization',
    'premium.features.chromotherapy.benefit3': 'Personalized sequences',
    'premium.features.chromotherapy.benefit4': 'Colors based on emotional state',

    'premium.features.sounds.title': 'Complete Library',
    'premium.features.sounds.description': 'Over 50 sounds + Spotify integration',
    'premium.features.sounds.benefit1': 'Therapeutic binaural frequencies',
    'premium.features.sounds.benefit2': 'Full Spotify integration',
    'premium.features.sounds.benefit3': 'High-quality sounds',
    'premium.features.sounds.benefit4': 'Expert-curated playlists',

    'premium.features.ai.title': 'AI Recommendations',
    'premium.features.ai.description': 'Personalized artificial intelligence',
    'premium.features.ai.benefit1': 'Behavioral pattern analysis',
    'premium.features.ai.benefit2': 'Personalized recommendations',
    'premium.features.ai.benefit3': 'Automatic session optimization',
    'premium.features.ai.benefit4': 'Predictive wellness insights',

    'premium.features.offline.title': 'Offline Mode',
    'premium.features.offline.description': 'Full functionality without internet',
    'premium.features.offline.benefit1': 'Automatic synchronization',
    'premium.features.offline.benefit2': 'Smart content caching',
    'premium.features.offline.benefit3': 'Complete offline sessions',
    'premium.features.offline.benefit4': 'Automatic data backup',

    'premium.plans.title': 'Premium Plans',
    'premium.plans.subtitle': 'Choose the ideal plan for your needs',
    'premium.plans.popular': 'Most Popular',
    'premium.plans.save': 'Save',
    'premium.plans.choose': 'Choose Plan',

    'premium.plans.monthly.name': 'Monthly Premium',
    'premium.plans.monthly.period': '/month',
    'premium.plans.monthly.feature1': 'All premium points',
    'premium.plans.monthly.feature2': 'WhatsApp consultation',
    'premium.plans.monthly.feature3': 'Exclusive sounds',
    'premium.plans.monthly.feature4': 'Advanced chromotherapy',
    'premium.plans.monthly.feature5': 'Priority support',

    'premium.plans.annual.name': 'Annual Premium',
    'premium.plans.annual.period': '/year',
    'premium.plans.annual.feature1': 'Everything in monthly plan',
    'premium.plans.annual.feature2': '2 months free',
    'premium.plans.annual.feature3': 'AI recommendations',
    'premium.plans.annual.feature4': 'Advanced analytics',
    'premium.plans.annual.feature5': 'Quarterly consulting',

    'premium.plans.lifetime.name': 'Lifetime Premium',
    'premium.plans.lifetime.period': 'one-time payment',
    'premium.plans.lifetime.feature1': 'Lifetime access',
    'premium.plans.lifetime.feature2': 'All future updates',
    'premium.plans.lifetime.feature3': 'VIP support',
    'premium.plans.lifetime.feature4': 'Unlimited consulting',
    'premium.plans.lifetime.feature5': 'Beta access to new features',

    'premium.payment.title': 'Complete Payment',
    'premium.payment.methods': 'Payment Methods',
    'premium.payment.back': 'Back to Plans',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Instant and secure',
    'premium.payment.pix.title': 'PIX Payment',
    'premium.payment.credit': 'Card',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Cryptocurrency Payment',

    'premium.testimonials.title': 'What our users say',
    'premium.testimonials.maria': 'Transformed my life! Acupressure relieved my chronic pain in just weeks.',
    'premium.testimonials.joao': '4-7-8 breathing helped me control my anxiety. I recommend it to everyone!',
    'premium.testimonials.ana': 'Excellent for corporate use. Our team is much more relaxed and productive.',

    'premium.faq.title': 'Frequently Asked Questions',
    'premium.faq.q1': 'Can I cancel anytime?',
    'premium.faq.a1': 'Yes, you can cancel your subscription at any time without additional fees.',
    'premium.faq.q2': 'Are premium points safe?',
    'premium.faq.a2': 'All points are based on Traditional Chinese Medicine with 15+ years of clinical experience.',
    'premium.faq.q3': 'Does it work offline?',
    'premium.faq.a3': 'Yes, the premium version includes full offline mode with automatic synchronization.',
    'premium.faq.q4': 'Is there a results guarantee?',
    'premium.faq.a4': 'We offer a 30-day guarantee. If not satisfied, we refund your money.',

    // Corporate Page
    'corporate.hero.title': 'Corporate Solutions',
    'corporate.hero.subtitle': 'Integrative wellness for companies with complete legal compliance',
    'corporate.plans.title': 'Corporate Plans',
    'corporate.analytics.title': 'Business Analytics',
    'corporate.roi.title': 'Proven ROI',
    'corporate.roi.subtitle': 'Measurable results in corporate wellness',
    'corporate.roi.stress': 'Stress reduction',
    'corporate.roi.absences': 'Fewer absences',
    'corporate.roi.engagement': 'Greater engagement',
    'corporate.roi.return': 'Return on investment',

    // Login Page
    'login.welcome': 'Welcome back',
    'login.createAccount': 'Create Account',
    'login.subtitle.login': 'Sign in to your account to access all features',
    'login.subtitle.register': 'Create your account and start your wellness journey',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Confirm Password',
    'login.name': 'Name',
    'login.forgotPassword': 'Forgot password',
    'login.noAccount': 'No account? Sign up',
    'login.hasAccount': 'Already have account? Sign in',
    'login.demo.title': 'Demo Mode',
    'login.demo.desc': 'Use any valid email + password with 6+ characters',
    'login.reset.title': 'Reset Password',
    'login.reset.subtitle': 'Enter your email to receive instructions',
    'login.reset.send': 'Send Email',
    'login.reset.back': 'Back to Login',

    // WhatsApp Consultation
    'whatsapp.back': 'Back',
    'whatsapp.consultation.title': 'Specialized Consultation',
    'whatsapp.consultation.description': 'Detailed form for personalized WhatsApp care',
    'whatsapp.features.specialized.title': 'Specialized Care',
    'whatsapp.features.specialized.subtitle': 'Complex cases requiring individual attention',
    'whatsapp.features.specialized.professional': 'Professional with 15+ years experience',
    'whatsapp.features.fast.title': 'Fast Response',
    'whatsapp.features.fast.subtitle': 'Maximum response priority',
    'whatsapp.features.direct.title': 'Direct WhatsApp',
    'whatsapp.features.direct.subtitle': 'Direct and personalized communication',
    'whatsapp.when.title': 'When to Seek Help',
    'whatsapp.when.chronic': 'Chronic pain that doesn\'t improve',
    'whatsapp.when.neurological': 'Complex neurological problems',
    'whatsapp.when.nonresponsive': 'Cases not responding to basic points',
    'whatsapp.when.personalized': 'Need for personalized protocol',
    'whatsapp.testimonial.text': 'Exceptional care! Solved my chronic pain in just a few sessions.',
    'whatsapp.testimonial.author': 'Maria S., São Paulo',
    'whatsapp.form.title': 'Consultation Form',
    'whatsapp.form.subtitle': 'Fill in the details below to receive specialized care',
    'whatsapp.form.name': 'Full Name',
    'whatsapp.form.name.placeholder': 'Your full name',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'your@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '(11) 99999-9999',
    'whatsapp.form.urgency': 'Urgency Level',
    'whatsapp.form.urgency.select': 'Select urgency',
    'whatsapp.form.urgency.low': 'Low - Preventive consultation',
    'whatsapp.form.urgency.medium': 'Medium - Moderate discomfort',
    'whatsapp.form.urgency.high': 'High - Significant pain',
    'whatsapp.form.urgency.urgent': 'Urgent - Intense pain',
    'whatsapp.form.medical.title': 'Medical Information',
    'whatsapp.form.medical.condition': 'Main Condition',
    'whatsapp.form.medical.condition.placeholder': 'E.g.: Chronic migraine, anxiety, back pain',
    'whatsapp.form.medical.duration': 'How long have you had symptoms?',
    'whatsapp.form.medical.duration.placeholder': 'E.g.: 2 years, 6 months, since childhood',
    'whatsapp.form.medical.symptoms': 'Detailed Symptom Description',
    'whatsapp.form.medical.symptoms.placeholder': 'Describe your symptoms in detail, when they appear, intensity, etc.',
    'whatsapp.form.medical.treatments': 'Previous Treatments',
    'whatsapp.form.medical.treatments.placeholder': 'Medications, therapies, surgeries, etc.',
    'whatsapp.form.medical.medications': 'Current Medications',
    'whatsapp.form.medical.medications.placeholder': 'List all medications you currently use',
    'whatsapp.form.medical.schedule': 'Preferred Time',
    'whatsapp.form.medical.schedule.select': 'Select best time',
    'whatsapp.form.medical.schedule.morning': 'Morning (8am-12pm)',
    'whatsapp.form.medical.schedule.afternoon': 'Afternoon (12pm-6pm)',
    'whatsapp.form.medical.schedule.evening': 'Evening (6pm-10pm)',
    'whatsapp.form.medical.schedule.anytime': 'Anytime',
    'whatsapp.form.notice.title': 'Important',
    'whatsapp.form.notice.text': 'This form will be sent directly to our specialist via WhatsApp',
    'whatsapp.form.submit': 'Send to WhatsApp',
    'whatsapp.form.redirect': 'You will be redirected to WhatsApp with your message ready'
  },

  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.acupressure': 'Acupresión',
    'nav.breathing': 'Respiración',
    'nav.premium': 'Premium',
    'nav.corporate': 'Corporativo',
    'nav.blog': 'Blog',
    'nav.dashboard': 'Panel',
    'nav.sounds': 'Sonidos',
    'nav.progress': 'Progreso',
    'nav.personalization': 'Personalización',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',

    // Home Page
    'home.hero.title': 'XZenPress Bienestar',
    'home.hero.subtitle': 'Plataforma completa de bienestar integrativo con acupresión MTC, Craniopuntura, respiración 4-7-8 y cromoterapia avanzada',
    'home.hero.startNow': 'Comenzar Ahora',
    'home.hero.createAccount': 'Crear Cuenta',

    // Home Features
    'home.feature.acupressure.title': 'Acupresión MTC',
    'home.feature.acupressure.desc': '20 puntos terapéuticos de Medicina Tradicional China para alivio natural',
    'home.feature.breathing.title': 'Respiración 4-7-8',
    'home.feature.breathing.desc': 'Técnica científica de respiración con cromoterapia sincronizada',
    'home.feature.cranio.title': 'Craniopuntura',
    'home.feature.cranio.desc': 'Puntos especializados para sistema nervioso y función cerebral',
    'home.feature.chromotherapy.title': 'Cromoterapia Avanzada',
    'home.feature.chromotherapy.desc': 'Colores terapéuticos sincronizados con respiración para potenciar efectos',
    'home.feature.sounds.title': 'Sonidos Armonizantes',
    'home.feature.sounds.desc': 'Biblioteca de sonidos relajantes con integración Spotify Premium',
    'home.feature.consultation.title': 'Consulta Especializada',
    'home.feature.consultation.desc': 'Atención personalizada vía WhatsApp con profesional calificado',

    'home.features.title': 'Recursos Terapéuticos',
    'home.features.subtitle': 'Combina técnicas milenarias con tecnología moderna para máximo bienestar integrativo',

    'home.cta.title': 'Transforma tu Calidad de Vida',
    'home.cta.subtitle': 'Únete a miles que han descubierto el poder de las terapias integrativas',
    'home.cta.demo': 'Probar Gratis',
    'home.cta.corporate': 'Soluciones Corporativas',

    'home.compliance.title': 'Cumplimiento Legal Completo',
    'home.compliance.subtitle': 'Cumplimiento integral con legislación brasileña de salud mental corporativa con enfoque integrativo',

    // Acupressure Page
    'acupressure.title': 'Puntos de Acupresión',
    'acupressure.subtitle': 'Medicina Tradicional China y Craniopuntura con terapia integrativa: acupresión + respiración + cromoterapia',
    'acupressure.categories.all': 'Todos los Puntos',
    'acupressure.categories.general': 'MTC General',
    'acupressure.categories.cranio': 'Craniopuntura',
    'acupressure.categories.septicemia': 'Septicemia',
    'acupressure.categories.atm': 'ATM',
    'acupressure.select.title': 'Seleccione un Punto',
    'acupressure.select.subtitle': 'Haga clic en un punto para ver detalles e iniciar terapia integrada',
    'acupressure.timer.start': 'Iniciar Terapia Integrada',
    'acupressure.timer.active': 'Terapia en Progreso',
    'acupressure.timer.switch': 'Cambiar a Este Punto',

    // Breathing Exercise
    'breathing.title': 'Respiración 4-7-8 con Cromoterapia',
    'breathing.inhale': 'Inhalar',
    'breathing.hold': 'Retener',
    'breathing.exhale': 'Exhalar',
    'breathing.start': 'Iniciar Respiración',
    'breathing.stop': 'Parar',
    'breathing.reset': 'Reiniciar',
    'breathing.totalTime': 'Tiempo Total',
    'breathing.phase': 'Fase',
    'breathing.phase.inhale.detail': 'Inhalación con azul calmante',
    'breathing.phase.hold.detail': 'Retención con verde equilibrante',
    'breathing.phase.exhale.detail': 'Exhalación con púrpura energizante',

    'breathing.chromotherapy.title': 'Cromoterapia Científica',
    'breathing.chromotherapy.description': 'Colores terapéuticos sincronizados con cada fase de respiración para potenciar efectos',
    'breathing.chromotherapy.blue': 'Azul Calmante',
    'breathing.chromotherapy.blue.desc': 'Activa sistema parasimpático, reduce presión arterial y promueve relajación profunda',
    'breathing.chromotherapy.green': 'Verde Equilibrante',
    'breathing.chromotherapy.green.desc': 'Equilibra sistema nervioso, armoniza emociones y promueve estabilidad',
    'breathing.chromotherapy.magenta': 'Púrpura Energizante',
    'breathing.chromotherapy.magenta.desc': 'Estimula liberación de endorfinas y promueve transformación energética',

    'breathing.benefits.title': 'Beneficios Comprobados',
    'breathing.benefits.stress': 'Reduce estrés y ansiedad',
    'breathing.benefits.sleep': 'Mejora calidad del sueño',
    'breathing.benefits.focus': 'Aumenta enfoque y concentración',
    'breathing.benefits.pressure': 'Reduce presión arterial',

    'breathing.science.title': 'Base Científica',
    'breathing.science.evidence': 'Evidencia Científica',
    'breathing.science.parasympathetic': 'Activa sistema parasimpático',
    'breathing.science.cortisol': 'Reduce niveles de cortisol',
    'breathing.science.heartRate': 'Mejora variabilidad cardíaca',
    'breathing.science.gaba': 'Aumenta producción de GABA',
    'breathing.science.chromotherapy': 'Cromoterapia Integrada',
    'breathing.science.blue.effect': 'Azul reduce presión arterial',
    'breathing.science.green.effect': 'Verde equilibra sistema nervioso',
    'breathing.science.magenta.effect': 'Púrpura estimula endorfinas',
    'breathing.science.melatonin': 'Mejora producción de melatonina',

    // Premium Page
    'premium.hero.title': 'Desbloquea Todo el Potencial',
    'premium.hero.subtitle': 'Acceso completo a consultas especializadas y recursos exclusivos de medicina integrativa',
    'premium.hero.upgrade': 'Actualizar Ahora',
    'premium.hero.active': 'Premium Activo',

    'premium.features.title': 'Funciones Premium',
    'premium.features.available': 'Disponible',
    'premium.features.coming': 'Próximamente',

    'premium.features.whatsapp.title': 'Consulta WhatsApp',
    'premium.features.whatsapp.description': 'Atención personalizada con profesional calificado',
    'premium.features.whatsapp.benefit1': 'Profesional con más de 15 años de experiencia',
    'premium.features.whatsapp.benefit2': 'Respuesta prioritaria en 24h',
    'premium.features.whatsapp.benefit3': 'Formulario detallado para casos complejos',
    'premium.features.whatsapp.benefit4': 'Seguimiento continuo del caso',

    'premium.features.points.title': 'Puntos Exclusivos',
    'premium.features.points.description': '11 puntos especializados para casos específicos',
    'premium.features.points.benefit1': 'Septicemia: 3 puntos para purificación',
    'premium.features.points.benefit2': 'ATM: 3 puntos para articulación',
    'premium.features.points.benefit3': 'Cranio: 3 puntos para sistema nervioso',
    'premium.features.points.benefit4': 'Neurología: 2 puntos avanzados',

    'premium.features.chromotherapy.title': 'Cromoterapia Avanzada',
    'premium.features.chromotherapy.description': 'Secuencias personalizadas de colores terapéuticos',
    'premium.features.chromotherapy.benefit1': 'Perfiles adaptativos de colores',
    'premium.features.chromotherapy.benefit2': 'Sincronización con biofeedback',
    'premium.features.chromotherapy.benefit3': 'Secuencias personalizadas',
    'premium.features.chromotherapy.benefit4': 'Colores basados en estado emocional',

    'premium.features.sounds.title': 'Biblioteca Completa',
    'premium.features.sounds.description': 'Más de 50 sonidos + integración Spotify',
    'premium.features.sounds.benefit1': 'Frecuencias binaurales terapéuticas',
    'premium.features.sounds.benefit2': 'Integración completa con Spotify',
    'premium.features.sounds.benefit3': 'Sonidos de alta calidad',
    'premium.features.sounds.benefit4': 'Listas seleccionadas por expertos',

    'premium.features.ai.title': 'Recomendaciones IA',
    'premium.features.ai.description': 'Inteligencia artificial personalizada',
    'premium.features.ai.benefit1': 'Análisis de patrones conductuales',
    'premium.features.ai.benefit2': 'Recomendaciones personalizadas',
    'premium.features.ai.benefit3': 'Optimización automática de sesiones',
    'premium.features.ai.benefit4': 'Insights predictivos de bienestar',

    'premium.features.offline.title': 'Modo Sin Conexión',
    'premium.features.offline.description': 'Funcionalidad completa sin internet',
    'premium.features.offline.benefit1': 'Sincronización automática',
    'premium.features.offline.benefit2': 'Caché inteligente de contenido',
    'premium.features.offline.benefit3': 'Sesiones offline completas',
    'premium.features.offline.benefit4': 'Respaldo automático de datos',

    'premium.plans.title': 'Planes Premium',
    'premium.plans.subtitle': 'Elige el plan ideal para tus necesidades',
    'premium.plans.popular': 'Más Popular',
    'premium.plans.save': 'Ahorra',
    'premium.plans.choose': 'Elegir Plan',

    'premium.plans.monthly.name': 'Premium Mensual',
    'premium.plans.monthly.period': '/mes',
    'premium.plans.monthly.feature1': 'Todos los puntos premium',
    'premium.plans.monthly.feature2': 'Consulta WhatsApp',
    'premium.plans.monthly.feature3': 'Sonidos exclusivos',
    'premium.plans.monthly.feature4': 'Cromoterapia avanzada',
    'premium.plans.monthly.feature5': 'Soporte prioritario',

    'premium.plans.annual.name': 'Premium Anual',
    'premium.plans.annual.period': '/año',
    'premium.plans.annual.feature1': 'Todo del plan mensual',
    'premium.plans.annual.feature2': '2 meses gratis',
    'premium.plans.annual.feature3': 'Recomendaciones IA',
    'premium.plans.annual.feature4': 'Analytics avanzados',
    'premium.plans.annual.feature5': 'Consultoría trimestral',

    'premium.plans.lifetime.name': 'Premium Vitalicio',
    'premium.plans.lifetime.period': 'pago único',
    'premium.plans.lifetime.feature1': 'Acceso vitalicio',
    'premium.plans.lifetime.feature2': 'Todas las actualizaciones futuras',
    'premium.plans.lifetime.feature3': 'Soporte VIP',
    'premium.plans.lifetime.feature4': 'Consultoría ilimitada',
    'premium.plans.lifetime.feature5': 'Acceso beta a nuevas funciones',

    'premium.payment.title': 'Completar Pago',
    'premium.payment.methods': 'Métodos de Pago',
    'premium.payment.back': 'Volver a Planes',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Instantáneo y seguro',
    'premium.payment.pix.title': 'Pago vía PIX',
    'premium.payment.credit': 'Tarjeta',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Pago con Criptomonedas',

    'premium.testimonials.title': 'Lo que dicen nuestros usuarios',
    'premium.testimonials.maria': '¡Transformó mi vida! La acupresión alivió mis dolores crónicos en pocas semanas.',
    'premium.testimonials.joao': 'La respiración 4-7-8 me ayudó a controlar mi ansiedad. ¡Lo recomiendo a todos!',
    'premium.testimonials.ana': 'Excelente para uso corporativo. Nuestro equipo está mucho más relajado y productivo.',

    'premium.faq.title': 'Preguntas Frecuentes',
    'premium.faq.q1': '¿Puedo cancelar en cualquier momento?',
    'premium.faq.a1': 'Sí, puedes cancelar tu suscripción en cualquier momento sin cargos adicionales.',
    'premium.faq.q2': '¿Son seguros los puntos premium?',
    'premium.faq.a2': 'Todos los puntos están basados en Medicina Tradicional China con más de 15 años de experiencia clínica.',
    'premium.faq.q3': '¿Funciona sin conexión?',
    'premium.faq.a3': 'Sí, la versión premium incluye modo sin conexión completo con sincronización automática.',
    'premium.faq.q4': '¿Hay garantía de resultados?',
    'premium.faq.a4': 'Ofrecemos garantía de 30 días. Si no estás satisfecho, devolvemos tu dinero.',

    // Corporate Page
    'corporate.hero.title': 'Soluciones Corporativas',
    'corporate.hero.subtitle': 'Bienestar integrativo para empresas con cumplimiento legal completo',
    'corporate.plans.title': 'Planes Corporativos',
    'corporate.analytics.title': 'Analytics Empresariales',
    'corporate.roi.title': 'ROI Comprobado',
    'corporate.roi.subtitle': 'Resultados medibles en bienestar corporativo',
    'corporate.roi.stress': 'Reducción del estrés',
    'corporate.roi.absences': 'Menos ausencias',
    'corporate.roi.engagement': 'Mayor compromiso',
    'corporate.roi.return': 'Retorno de inversión',

    // Login Page
    'login.welcome': 'Bienvenido de nuevo',
    'login.createAccount': 'Crear Cuenta',
    'login.subtitle.login': 'Inicia sesión en tu cuenta para acceder a todas las funciones',
    'login.subtitle.register': 'Crea tu cuenta y comienza tu viaje de bienestar',
    'login.email': 'Email',
    'login.password': 'Contraseña',
    'login.confirmPassword': 'Confirmar Contraseña',
    'login.name': 'Nombre',
    'login.forgotPassword': 'Olvidé mi contraseña',
    'login.noAccount': '¿No tienes cuenta? Regístrate',
    'login.hasAccount': '¿Ya tienes cuenta? Inicia sesión',
    'login.demo.title': 'Modo Demostración',
    'login.demo.desc': 'Usa cualquier email válido + contraseña con 6+ caracteres',
    'login.reset.title': 'Recuperar Contraseña',
    'login.reset.subtitle': 'Ingresa tu email para recibir instrucciones',
    'login.reset.send': 'Enviar Email',
    'login.reset.back': 'Volver al Inicio de Sesión',

    // WhatsApp Consultation
    'whatsapp.back': 'Volver',
    'whatsapp.consultation.title': 'Consulta Especializada',
    'whatsapp.consultation.description': 'Formulario detallado para atención personalizada vía WhatsApp',
    'whatsapp.features.specialized.title': 'Atención Especializada',
    'whatsapp.features.specialized.subtitle': 'Casos complejos que requieren atención individual',
    'whatsapp.features.specialized.professional': 'Profesional con más de 15 años de experiencia',
    'whatsapp.features.fast.title': 'Respuesta Rápida',
    'whatsapp.features.fast.subtitle': 'Máxima prioridad de respuesta',
    'whatsapp.features.direct.title': 'WhatsApp Directo',
    'whatsapp.features.direct.subtitle': 'Comunicación directa y personalizada',
    'whatsapp.when.title': 'Cuándo Buscar Ayuda',
    'whatsapp.when.chronic': 'Dolores crónicos que no mejoran',
    'whatsapp.when.neurological': 'Problemas neurológicos complejos',
    'whatsapp.when.nonresponsive': 'Casos que no responden a puntos básicos',
    'whatsapp.when.personalized': 'Necesidad de protocolo personalizado',
    'whatsapp.testimonial.text': '¡Atención excepcional! Resolvió mi dolor crónico en pocas sesiones.',
    'whatsapp.testimonial.author': 'María S., São Paulo',
    'whatsapp.form.title': 'Formulario de Consulta',
    'whatsapp.form.subtitle': 'Completa los datos a continuación para recibir atención especializada',
    'whatsapp.form.name': 'Nombre Completo',
    'whatsapp.form.name.placeholder': 'Tu nombre completo',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'tu@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '(11) 99999-9999',
    'whatsapp.form.urgency': 'Nivel de Urgencia',
    'whatsapp.form.urgency.select': 'Selecciona la urgencia',
    'whatsapp.form.urgency.low': 'Baja - Consulta preventiva',
    'whatsapp.form.urgency.medium': 'Media - Molestia moderada',
    'whatsapp.form.urgency.high': 'Alta - Dolor significativo',
    'whatsapp.form.urgency.urgent': 'Urgente - Dolor intenso',
    'whatsapp.form.medical.title': 'Información Médica',
    'whatsapp.form.medical.condition': 'Condición Principal',
    'whatsapp.form.medical.condition.placeholder': 'Ej: Migraña crónica, ansiedad, dolor de espalda',
    'whatsapp.form.medical.duration': '¿Cuánto tiempo tienes los síntomas?',
    'whatsapp.form.medical.duration.placeholder': 'Ej: 2 años, 6 meses, desde la infancia',
    'whatsapp.form.medical.symptoms': 'Descripción Detallada de Síntomas',
    'whatsapp.form.medical.symptoms.placeholder': 'Describe tus síntomas en detalle, cuándo aparecen, intensidad, etc.',
    'whatsapp.form.medical.treatments': 'Tratamientos Previos',
    'whatsapp.form.medical.treatments.placeholder': 'Medicamentos, terapias, cirugías, etc.',
    'whatsapp.form.medical.medications': 'Medicamentos Actuales',
    'whatsapp.form.medical.medications.placeholder': 'Lista todos los medicamentos que usas actualmente',
    'whatsapp.form.medical.schedule': 'Horario Preferido',
    'whatsapp.form.medical.schedule.select': 'Selecciona el mejor horario',
    'whatsapp.form.medical.schedule.morning': 'Mañana (8h-12h)',
    'whatsapp.form.medical.schedule.afternoon': 'Tarde (12h-18h)',
    'whatsapp.form.medical.schedule.evening': 'Noche (18h-22h)',
    'whatsapp.form.medical.schedule.anytime': 'Cualquier horario',
    'whatsapp.form.notice.title': 'Importante',
    'whatsapp.form.notice.text': 'Este formulario será enviado directamente a nuestro especialista vía WhatsApp',
    'whatsapp.form.submit': 'Enviar a WhatsApp',
    'whatsapp.form.redirect': 'Serás redirigido a WhatsApp con tu mensaje listo'
  },

  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.acupressure': 'Agopressione',
    'nav.breathing': 'Respirazione',
    'nav.premium': 'Premium',
    'nav.corporate': 'Aziendale',
    'nav.blog': 'Blog',
    'nav.dashboard': 'Dashboard',
    'nav.sounds': 'Suoni',
    'nav.progress': 'Progresso',
    'nav.personalization': 'Personalizzazione',
    'nav.login': 'Accedi',
    'nav.logout': 'Esci',

    // Home Page
    'home.hero.title': 'XZenPress Benessere',
    'home.hero.subtitle': 'Piattaforma completa di benessere integrativo con agopressione MTC, Craniopuntura, respirazione 4-7-8 e cromoterapia avanzata',
    'home.hero.startNow': 'Inizia Ora',
    'home.hero.createAccount': 'Crea Account',

    // Home Features
    'home.feature.acupressure.title': 'Agopressione MTC',
    'home.feature.acupressure.desc': '20 punti terapeutici della Medicina Tradizionale Cinese per sollievo naturale',
    'home.feature.breathing.title': 'Respirazione 4-7-8',
    'home.feature.breathing.desc': 'Tecnica scientifica di respirazione con cromoterapia sincronizzata',
    'home.feature.cranio.title': 'Craniopuntura',
    'home.feature.cranio.desc': 'Punti specializzati per sistema nervoso e funzione cerebrale',
    'home.feature.chromotherapy.title': 'Cromoterapia Avanzata',
    'home.feature.chromotherapy.desc': 'Colori terapeutici sincronizzati con la respirazione per potenziare gli effetti',
    'home.feature.sounds.title': 'Suoni Armonizzanti',
    'home.feature.sounds.desc': 'Biblioteca di suoni rilassanti con integrazione Spotify Premium',
    'home.feature.consultation.title': 'Consulenza Specializzata',
    'home.feature.consultation.desc': 'Assistenza personalizzata via WhatsApp con professionista qualificato',

    'home.features.title': 'Risorse Terapeutiche',
    'home.features.subtitle': 'Combina tecniche millenarie con tecnologia moderna per il massimo benessere integrativo',

    'home.cta.title': 'Trasforma la Tua Qualità di Vita',
    'home.cta.subtitle': 'Unisciti a migliaia di persone che hanno scoperto il potere delle terapie integrative',
    'home.cta.demo': 'Prova Gratis',
    'home.cta.corporate': 'Soluzioni Aziendali',

    'home.compliance.title': 'Conformità Legale Completa',
    'home.compliance.subtitle': 'Piena conformità con la legislazione brasiliana sulla salute mentale aziendale con approccio integrativo',

    // Acupressure Page
    'acupressure.title': 'Punti di Agopressione',
    'acupressure.subtitle': 'Medicina Tradizionale Cinese e Craniopuntura con terapia integrativa: agopressione + respirazione + cromoterapia',
    'acupressure.categories.all': 'Tutti i Punti',
    'acupressure.categories.general': 'MTC Generale',
    'acupressure.categories.cranio': 'Craniopuntura',
    'acupressure.categories.septicemia': 'Setticemia',
    'acupressure.categories.atm': 'ATM',
    'acupressure.select.title': 'Seleziona un Punto',
    'acupressure.select.subtitle': 'Clicca su un punto per vedere i dettagli e iniziare la terapia integrata',
    'acupressure.timer.start': 'Inizia Terapia Integrata',
    'acupressure.timer.active': 'Terapia in Corso',
    'acupressure.timer.switch': 'Passa a Questo Punto',

    // Breathing Exercise
    'breathing.title': 'Respirazione 4-7-8 con Cromoterapia',
    'breathing.inhale': 'Inspira',
    'breathing.hold': 'Trattieni',
    'breathing.exhale': 'Espira',
    'breathing.start': 'Inizia Respirazione',
    'breathing.stop': 'Ferma',
    'breathing.reset': 'Riavvia',
    'breathing.totalTime': 'Tempo Totale',
    'breathing.phase': 'Fase',
    'breathing.phase.inhale.detail': 'Inspirazione con blu calmante',
    'breathing.phase.hold.detail': 'Ritenzione con verde equilibrante',
    'breathing.phase.exhale.detail': 'Espirazione con viola energizzante',

    'breathing.chromotherapy.title': 'Cromoterapia Scientifica',
    'breathing.chromotherapy.description': 'Colori terapeutici sincronizzati con ogni fase della respirazione per potenziare gli effetti',
    'breathing.chromotherapy.blue': 'Blu Calmante',
    'breathing.chromotherapy.blue.desc': 'Attiva il sistema parasimpatico, riduce la pressione sanguigna e promuove il rilassamento profondo',
    'breathing.chromotherapy.green': 'Verde Equilibrante',
    'breathing.chromotherapy.green.desc': 'Equilibra il sistema nervoso, armonizza le emozioni e promuove la stabilità',
    'breathing.chromotherapy.magenta': 'Viola Energizzante',
    'breathing.chromotherapy.magenta.desc': 'Stimola il rilascio di endorfine e promuove la trasformazione energetica',

    'breathing.benefits.title': 'Benefici Comprovati',
    'breathing.benefits.stress': 'Riduce stress e ansia',
    'breathing.benefits.sleep': 'Migliora la qualità del sonno',
    'breathing.benefits.focus': 'Aumenta focus e concentrazione',
    'breathing.benefits.pressure': 'Riduce la pressione sanguigna',

    'breathing.science.title': 'Base Scientifica',
    'breathing.science.evidence': 'Evidenze Scientifiche',
    'breathing.science.parasympathetic': 'Attiva il sistema parasimpatico',
    'breathing.science.cortisol': 'Riduce i livelli di cortisolo',
    'breathing.science.heartRate': 'Migliora la variabilità cardiaca',
    'breathing.science.gaba': 'Aumenta la produzione di GABA',
    'breathing.science.chromotherapy': 'Cromoterapia Integrata',
    'breathing.science.blue.effect': 'Il blu riduce la pressione sanguigna',
    'breathing.science.green.effect': 'Il verde equilibra il sistema nervoso',
    'breathing.science.magenta.effect': 'Il viola stimola le endorfine',
    'breathing.science.melatonin': 'Migliora la produzione di melatonina',

    // Premium Page
    'premium.hero.title': 'Sblocca Tutto il Potenziale',
    'premium.hero.subtitle': 'Accesso completo a consulenze specializzate e risorse esclusive di medicina integrativa',
    'premium.hero.upgrade': 'Aggiorna Ora',
    'premium.hero.active': 'Premium Attivo',

    'premium.features.title': 'Funzionalità Premium',
    'premium.features.available': 'Disponibile',
    'premium.features.coming': 'Prossimamente',

    'premium.features.whatsapp.title': 'Consulenza WhatsApp',
    'premium.features.whatsapp.description': 'Assistenza personalizzata con professionista qualificato',
    'premium.features.whatsapp.benefit1': 'Professionista con oltre 15 anni di esperienza',
    'premium.features.whatsapp.benefit2': 'Risposta prioritaria entro 24h',
    'premium.features.whatsapp.benefit3': 'Modulo dettagliato per casi complessi',
    'premium.features.whatsapp.benefit4': 'Monitoraggio continuo del caso',

    'premium.features.points.title': 'Punti Esclusivi',
    'premium.features.points.description': '11 punti specializzati per casi specifici',
    'premium.features.points.benefit1': 'Setticemia: 3 punti per la purificazione',
    'premium.features.points.benefit2': 'ATM: 3 punti per l\'articolazione',
    'premium.features.points.benefit3': 'Cranio: 3 punti per il sistema nervoso',
    'premium.features.points.benefit4': 'Neurologia: 2 punti avanzati',

    'premium.features.chromotherapy.title': 'Cromoterapia Avanzata',
    'premium.features.chromotherapy.description': 'Sequenze personalizzate di colori terapeutici',
    'premium.features.chromotherapy.benefit1': 'Profili adattivi di colori',
    'premium.features.chromotherapy.benefit2': 'Sincronizzazione con biofeedback',
    'premium.features.chromotherapy.benefit3': 'Sequenze personalizzate',
    'premium.features.chromotherapy.benefit4': 'Colori basati sullo stato emotivo',

    'premium.features.sounds.title': 'Biblioteca Completa',
    'premium.features.sounds.description': 'Oltre 50 suoni + integrazione Spotify',
    'premium.features.sounds.benefit1': 'Frequenze binaurali terapeutiche',
    'premium.features.sounds.benefit2': 'Integrazione completa con Spotify',
    'premium.features.sounds.benefit3': 'Suoni di alta qualità',
    'premium.features.sounds.benefit4': 'Playlist curate da esperti',

    'premium.features.ai.title': 'Raccomandazioni IA',
    'premium.features.ai.description': 'Intelligenza artificiale personalizzata',
    'premium.features.ai.benefit1': 'Analisi dei pattern comportamentali',
    'premium.features.ai.benefit2': 'Raccomandazioni personalizzate',
    'premium.features.ai.benefit3': 'Ottimizzazione automatica delle sessioni',
    'premium.features.ai.benefit4': 'Approfondimenti predittivi sul benessere',

    'premium.features.offline.title': 'Modalità Offline',
    'premium.features.offline.description': 'Funzionalità complete senza internet',
    'premium.features.offline.benefit1': 'Sincronizzazione automatica',
    'premium.features.offline.benefit2': 'Cache intelligente dei contenuti',
    'premium.features.offline.benefit3': 'Sessioni offline complete',
    'premium.features.offline.benefit4': 'Backup automatico dei dati',

    'premium.plans.title': 'Piani Premium',
    'premium.plans.subtitle': 'Scegli il piano ideale per le tue esigenze',
    'premium.plans.popular': 'Più Popolare',
    'premium.plans.save': 'Risparmia',
    'premium.plans.choose': 'Scegli Piano',

    'premium.plans.monthly.name': 'Premium Mensile',
    'premium.plans.monthly.period': '/mese',
    'premium.plans.monthly.feature1': 'Tutti i punti premium',
    'premium.plans.monthly.feature2': 'Consulenza WhatsApp',
    'premium.plans.monthly.feature3': 'Suoni esclusivi',
    'premium.plans.monthly.feature4': 'Cromoterapia avanzata',
    'premium.plans.monthly.feature5': 'Supporto prioritario',

    'premium.plans.annual.name': 'Premium Annuale',
    'premium.plans.annual.period': '/anno',
    'premium.plans.annual.feature1': 'Tutto del piano mensile',
    'premium.plans.annual.feature2': '2 mesi gratis',
    'premium.plans.annual.feature3': 'Raccomandazioni IA',
    'premium.plans.annual.feature4': 'Analytics avanzati',
    'premium.plans.annual.feature5': 'Consulenza trimestrale',

    'premium.plans.lifetime.name': 'Premium Lifetime',
    'premium.plans.lifetime.period': 'pagamento unico',
    'premium.plans.lifetime.feature1': 'Accesso a vita',
    'premium.plans.lifetime.feature2': 'Tutti gli aggiornamenti futuri',
    'premium.plans.lifetime.feature3': 'Supporto VIP',
    'premium.plans.lifetime.feature4': 'Consulenza illimitata',
    'premium.plans.lifetime.feature5': 'Accesso beta alle nuove funzionalità',

    'premium.payment.title': 'Completa Pagamento',
    'premium.payment.methods': 'Metodi di Pagamento',
    'premium.payment.back': 'Torna ai Piani',
    'premium.payment.pix': 'PIX',
    'premium.payment.pix.desc': 'Istantaneo e sicuro',
    'premium.payment.pix.title': 'Pagamento via PIX',
    'premium.payment.credit': 'Carta',
    'premium.payment.credit.desc': 'Visa, Master, Amex',
    'premium.payment.crypto': 'Crypto',
    'premium.payment.crypto.desc': 'Bitcoin, Ethereum',
    'premium.payment.crypto.title': 'Pagamento con Criptovalute',

    'premium.testimonials.title': 'Cosa dicono i nostri utenti',
    'premium.testimonials.maria': 'Ha trasformato la mia vita! L\'agopressione ha alleviato i miei dolori cronici in poche settimane.',
    'premium.testimonials.joao': 'La respirazione 4-7-8 mi ha aiutato a controllare l\'ansia. Lo consiglio a tutti!',
    'premium.testimonials.ana': 'Eccellente per uso aziendale. Il nostro team è molto più rilassato e produttivo.',

    'premium.faq.title': 'Domande Frequenti',
    'premium.faq.q1': 'Posso cancellare in qualsiasi momento?',
    'premium.faq.a1': 'Sì, puoi cancellare il tuo abbonamento in qualsiasi momento senza costi aggiuntivi.',
    'premium.faq.q2': 'I punti premium sono sicuri?',
    'premium.faq.a2': 'Tutti i punti sono basati sulla Medicina Tradizionale Cinese con oltre 15 anni di esperienza clinica.',
    'premium.faq.q3': 'Funziona offline?',
    'premium.faq.a3': 'Sì, la versione premium include la modalità offline completa con sincronizzazione automatica.',
    'premium.faq.q4': 'C\'è una garanzia sui risultati?',
    'premium.faq.a4': 'Offriamo una garanzia di 30 giorni. Se non sei soddisfatto, rimborsiamo il tuo denaro.',

    // Corporate Page
    'corporate.hero.title': 'Soluzioni Aziendali',
    'corporate.hero.subtitle': 'Benessere integrativo per aziende con conformità legale completa',
    'corporate.plans.title': 'Piani Aziendali',
    'corporate.analytics.title': 'Analytics Aziendali',
    'corporate.roi.title': 'ROI Comprovato',
    'corporate.roi.subtitle': 'Risultati misurabili nel benessere aziendale',
    'corporate.roi.stress': 'Riduzione dello stress',
    'corporate.roi.absences': 'Meno assenze',
    'corporate.roi.engagement': 'Maggiore coinvolgimento',
    'corporate.roi.return': 'Ritorno sull\'investimento',

    // Login Page
    'login.welcome': 'Bentornato',
    'login.createAccount': 'Crea Account',
    'login.subtitle.login': 'Accedi al tuo account per accedere a tutte le funzionalità',
    'login.subtitle.register': 'Crea il tuo account e inizia il tuo viaggio di benessere',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.confirmPassword': 'Conferma Password',
    'login.name': 'Nome',
    'login.forgotPassword': 'Password dimenticata',
    'login.noAccount': 'Nessun account? Registrati',
    'login.hasAccount': 'Hai già un account? Accedi',
    'login.demo.title': 'Modalità Demo',
    'login.demo.desc': 'Usa qualsiasi email valida + password con 6+ caratteri',
    'login.reset.title': 'Reimposta Password',
    'login.reset.subtitle': 'Inserisci la tua email per ricevere istruzioni',
    'login.reset.send': 'Invia Email',
    'login.reset.back': 'Torna al Login',

    // WhatsApp Consultation
    'whatsapp.back': 'Indietro',
    'whatsapp.consultation.title': 'Consulenza Specializzata',
    'whatsapp.consultation.description': 'Modulo dettagliato per assistenza personalizzata via WhatsApp',
    'whatsapp.features.specialized.title': 'Assistenza Specializzata',
    'whatsapp.features.specialized.subtitle': 'Casi complessi che richiedono attenzione individuale',
    'whatsapp.features.specialized.professional': 'Professionista con oltre 15 anni di esperienza',
    'whatsapp.features.fast.title': 'Risposta Rapida',
    'whatsapp.features.fast.subtitle': 'Massima priorità di risposta',
    'whatsapp.features.direct.title': 'WhatsApp Diretto',
    'whatsapp.features.direct.subtitle': 'Comunicazione diretta e personalizzata',
    'whatsapp.when.title': 'Quando Cercare Aiuto',
    'whatsapp.when.chronic': 'Dolori cronici che non migliorano',
    'whatsapp.when.neurological': 'Problemi neurologici complessi',
    'whatsapp.when.nonresponsive': 'Casi che non rispondono ai punti di base',
    'whatsapp.when.personalized': 'Necessità di protocollo personalizzato',
    'whatsapp.testimonial.text': 'Assistenza eccezionale! Ha risolto il mio dolore cronico in poche sessioni.',
    'whatsapp.testimonial.author': 'Maria S., São Paulo',
    'whatsapp.form.title': 'Modulo di Consulenza',
    'whatsapp.form.subtitle': 'Compila i dati qui sotto per ricevere assistenza specializzata',
    'whatsapp.form.name': 'Nome Completo',
    'whatsapp.form.name.placeholder': 'Il tuo nome completo',
    'whatsapp.form.email': 'Email',
    'whatsapp.form.email.placeholder': 'tua@email.com',
    'whatsapp.form.whatsapp': 'WhatsApp',
    'whatsapp.form.whatsapp.placeholder': '(11) 99999-9999',
    'whatsapp.form.urgency': 'Livello di Urgenza',
    'whatsapp.form.urgency.select': 'Seleziona l\'urgenza',
    'whatsapp.form.urgency.low': 'Bassa - Consulenza preventiva',
    'whatsapp.form.urgency.medium': 'Media - Disagio moderato',
    'whatsapp.form.urgency.high': 'Alta - Dolore significativo',
    'whatsapp.form.urgency.urgent': 'Urgente - Dolore intenso',
    'whatsapp.form.medical.title': 'Informazioni Mediche',
    'whatsapp.form.medical.condition': 'Condizione Principale',
    'whatsapp.form.medical.condition.placeholder': 'Es.: Emicrania cronica, ansia, mal di schiena',
    'whatsapp.form.medical.duration': 'Da quanto tempo hai i sintomi?',
    'whatsapp.form.medical.duration.placeholder': 'Es.: 2 anni, 6 mesi, dall\'infanzia',
    'whatsapp.form.medical.symptoms': 'Descrizione Dettagliata dei Sintomi',
    'whatsapp.form.medical.symptoms.placeholder': 'Descrivi i tuoi sintomi in dettaglio, quando compaiono, intensità, ecc.',
    'whatsapp.form.medical.treatments': 'Trattamenti Precedenti',
    'whatsapp.form.medical.treatments.placeholder': 'Farmaci, terapie, interventi chirurgici, ecc.',
    'whatsapp.form.medical.medications': 'Farmaci Attuali',
    'whatsapp.form.medical.medications.placeholder': 'Elenca tutti i farmaci che usi attualmente',
    'whatsapp.form.medical.schedule': 'Orario Preferito',
    'whatsapp.form.medical.schedule.select': 'Seleziona il miglior orario',
    'whatsapp.form.medical.schedule.morning': 'Mattina (8h-12h)',
    'whatsapp.form.medical.schedule.afternoon': 'Pomeriggio (12h-18h)',
    'whatsapp.form.medical.schedule.evening': 'Sera (18h-22h)',
    'whatsapp.form.medical.schedule.anytime': 'Qualsiasi orario',
    'whatsapp.form.notice.title': 'Importante',
    'whatsapp.form.notice.text': 'Questo modulo verrà inviato direttamente al nostro specialista via WhatsApp',
    'whatsapp.form.submit': 'Invia a WhatsApp',
    'whatsapp.form.redirect': 'Sarai reindirizzato a WhatsApp con il tuo messaggio pronto'
  },
  fr: {},
  de: {},
  zh: {},
  ja: {},
  ru: {},
  hi: {},
  ar: {},
  bn: {}
};

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  const t = (key: string): string => {
    const langTranslations = translations[currentLanguage.code as keyof typeof translations];
    const translation = langTranslations?.[key as keyof typeof translations.pt];

    if (!translation) {
      // Fallback cascade: current language → English → Portuguese
      const enTranslation = translations.en[key as keyof typeof translations.pt];
      if (enTranslation) return enTranslation;

      const ptTranslation = translations.pt[key as keyof typeof translations.pt];
      if (ptTranslation) return ptTranslation;

      // Only log warning in development
      if (process.env.NODE_ENV === 'development') {
        console.warn(`Translation missing for: "${key}" in language: ${currentLanguage.code}`);
      }
      return key;
    }

    return translation;
  };

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', language.code);
  };

  React.useEffect(() => {
    const saved = localStorage.getItem('selectedLanguage');
    if (saved) {
      const language = languages.find(lang => lang.code === saved);
      if (language) {
        setCurrentLanguage(language);
      }
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
